apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/namespaces
  - ../base/nginx

helmCharts:
- name: reloader
  repo: https://stakater.github.io/stakater-charts
  version: "1.0.69"
  releaseName: reloader
  namespace: reloader