apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dapr-system

helmCharts:
- name: dapr
  repo: https://dapr.github.io/helm-charts/
  version: 1.12.4
  releaseName: dapr 
  valuesFile: values.yaml